### ISSUE TITLE
Support JSON file upload for bulk insert of records

### ISSUE THREAD

**Issue by kdhrubo** [9tigerio/db2rest#677]
### Discussed in https://github.com/kdhrubo/db2rest/discussions/612

<div type='discussions-op-text'>

<sup>Originally posted by **kdhrubo** May  8, 2024</sup>
1. Max file size of 5MB to be supported. 
2. This will be an async operation.
3. Records will be streamed in chunks. 
</div>

**Comment by Hackeemlunar** [comment]
Must the chunks be processed immediately or one can wait for the whole file to be built

**Comment by kdhrubo** [comment]
Please explain what do you mean?
Ideally it should be chunk based processing

**Comment by thadguidry** [comment]
Chunks should be processed as received.
One has to consider that someone MIGHT want to upload a 4gb JSON string into a DB column?
But I guess for this issue we can start with a maxFileSize = 5MB

Questions:
1. Whatever we do, for JSON processing anywhere in DB2Rest, we should never use `org.json` (which still has licensing issues) but instead `com.fasterxml.jackson.core`?
2. Perhaps we should expose a new parameter to allow specifying which JSON datatype is going to be used for the prepared statement insert? ([PostgreSQL has `json` and `jsonb`](https://www.postgresql.org/docs/17/datatype-json.html) and I have needed `json` to keep things exact and retain key ordering, but then other times needing `jsonb` so that indexing could be used for efficient, fast, jsonpath queries later on.)

**Comment by Hackeemlunar** [comment]
@kdhrubo I get it now.

@thadguidry The file upload insertion is already a type of bulk insertion. Bulk insertion currently happens on **/db/{tablename}/bulk, so what **/db/{tablename}/file endpoint for the file processing?
